### ISSUE TITLE
Name of the components are not clear

### ISSUE THREAD

**Issue by jasonnam** [ttkien/clean-architecture-with-swift-and-testing#11]
What does `Domain` means?
What does `UseCase` mean?

**Comment by ttkien** [comment]
I described in Readme file I applied Clean Architecture, which is following Robert C.Martin who has more than 60 years of experience on Software development. You can read
Clean Architecture at the blog: blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html

I think this blog can explain your questions.

**Comment by jasonnam** [comment]
I understand the architecture but I think they don't usually use the term use case directly. One of the most popular derivate of Clean Architecture is VIPER and it uses `input` and `output` for the concept. Could you give me some article where `UseCase` is used directly in the name? It is very interesting. Thanks!

**Comment by ttkien** [comment]
You can call them as UseCases or Interactors. Robert C.Martin mentions them in his book: https://www.amazon.com/Clean-Architecture-Craftsmans-Software-Structure/dp/0134494164

You can see it as the following image from his book:
https://photos.app.goo.gl/NGzVEWHTJ9kakhsGA

Quote from the above blog
> 
> Use Cases
> The software in this layer contains application specific business rules. It encapsulates and implements all of the use cases of the system. These use cases orchestrate the flow of data to and from the entities and direct those entities to use their enterprise-wide business rules to achieve the goals of the use case.
> 
> We do not expect changes in this layer to affect the entities. We also do not expect this layer to be affected by changes to externalities such as the database, the UI, or any of the common frameworks. This layer is isolated from such concerns.
> 
> We do, however, expect that changes to the operation of the application will affect the use-cases and therefore the software in this layer. If the details of a use-case change, then some code in this layer will certainly be affected.

**Comment by olivierobert** [comment]
@ttkien The initial clean code architecture principles were conceived primarily in the structure of [web applications](https://skillsmatter.com/skillscasts/2437-uncle-bob-web-architecture). Note the examples in the book is for a Java application. It's valid to use it for any kind of software applications. But the `UseCase` term is primarily found in web implementations hence the confusion from @jasonnam. 

In addition, most [iOS](https://clean-swift.com/clean-swift-ios-architecture/) [examples](https://hackernoon.com/introducing-clean-swift-architecture-vip-770a639ad7bf) out there also do not use this term. Instead, it's coined as `scenes` or simply `modules`. 

For instance, when applying React patterns to web applications, it differs from mobile applications (with React Natives). Containers are called `Pages` for web applications but `Screens` for mobile applications.

**Comment by ttkien** [comment]
> the UseCase term is primarily found in web implementations hence the confusion from @jasonnam.
I don't agree with you about this point. UseCases represent for activities of business, like Use cases diagram,... It maps to company business activity and independent from API, Database, UI, external libraries.... The core concept of Clean Architecture is to protect the business from the technology changes. In more details, The web application is just an UI layer in the Clean Architecture. We can create a Web Application, Mobile Application, Command line Interface to integrate with UseCase layer, like: suppose, in next 3 years, there is a new technology which is better than current one, you just create new UI Layer interface and keep the Use cases layer.
