### ISSUE TITLE
Mock data in main app targets

### ISSUE THREAD

**Issue by jasonnam** [ttkien/clean-architecture-with-swift-and-testing#12]
It must be avoided to include mocking data and related files to main target which will be built for production. MockUseCases framework must not be linked to main target.

**Comment by ttkien** [comment]
The reason is to guarantee I am able to develop the project when The network has a problem. 
Suppose that, the network is corrupted, I just switch the configure and continue my tasks

**Comment by jasonnam** [comment]
It is ok to have mock data. But it should not be included in the production app.

**Comment by ttkien** [comment]
I totally agree with you. And, it is easy to get rid of it from the production app
