### ISSUE TITLE
Does not scroll to next page on pan from bottom to top

### ISSUE THREAD

**Issue by jasonnam** [ttkien/clean-architecture-with-swift-and-testing#8]
Usually, on mobile platform scrolling should follow gestures.
Currently, the app scroll to next page on scrolling from bottom to top. But gesture from top to bottom to go to next page is expected.

**Comment by ttkien** [comment]
I think this is misunderstood on the document. I see the screenshot on documents and think thr document want to implement UIPagingViewController but different from direction.
