### ISSUE TITLE
Introducing unnecessary classes

### ISSUE THREAD

**Issue by jasonnam** [ttkien/clean-architecture-with-swift-and-testing#9]
These object are not doing any thing as an object. Also it is not clear the intention on initializing classes to use properties seems like a method. Also not clear why it needs to be a singleton object. Creating series of object for properties acting as static is unnecessary overhead.

```swift
class Theme {

  class Font {
    var large: UIFont = UIFont.boldSystemFont(ofSize: 21)
    var normal: UIFont = UIFont.systemFont(ofSize: 15)
    var small: UIFont = UIFont.systemFont(ofSize: 13)
  }

  class TextColor {
    var normalDark: UIColor = UIColor.black
    var detail: UIColor = UIColor.gray
    var normalWhite: UIColor = UIColor.white
  }

  class BackgroundColor {
    var normalRed: UIColor = UIColor(red: 210/255, green: 28/255, blue: 43/255, alpha: 0.8)
    var normalBlack: UIColor = UIColor.black
  }

  var fontSize: Font = Font()
  var textColor: TextColor = TextColor()
  var backgroundColor: BackgroundColor = BackgroundColor()
}
```

**Comment by jasonnam** [comment]
We can just use static method for fonts and colors.

```swift
class Theme {

  class Font {
    static var large: UIFont = UIFont.boldSystemFont(ofSize: 21)
    static var normal: UIFont = UIFont.systemFont(ofSize: 15)
    static var small: UIFont = UIFont.systemFont(ofSize: 13)
  }
}
```

Does exactly same thing without runtime overhead.

**Comment by ttkien** [comment]
I think we have different solutions (coding style) but I think they can work both. 
My solution like that because I think I can override a new theme object and use Dependency Inject to inject new theme at run time.
For example, The application can have 2 themes Light mode and Dark mode and depend on user configuration we can load a specific theme at run time
